// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Customer struct {
	ID               uuid.UUID      `json:"id"`
	FullName         sql.NullString `json:"full_name"`
	Email            sql.NullString `json:"email"`
	Password         sql.NullString `json:"password"`
	PhoneNumber      sql.NullString `json:"phone_number"`
	ConfirmationCode sql.NullString `json:"confirmation_code"`
	ConfirmationTime sql.NullTime   `json:"confirmation_time"`
	// When customer created
	CreatedAt time.Time `json:"created_at"`
	// When customer created
	UpdatedAt time.Time `json:"updated_at"`
}

type CustomerOrder struct {
	ID         uuid.UUID     `json:"id"`
	OrderTime  time.Time     `json:"order_time"`
	TimePaid   sql.NullTime  `json:"time_paid"`
	TotalPrice int64         `json:"total_price"`
	Discount   sql.NullInt32 `json:"discount"`
	FinalPrice int64         `json:"final_price"`
	CustomerID uuid.UUID     `json:"customer_id"`
	// When order created
	CreatedAt time.Time `json:"created_at"`
	// When order created
	UpdatedAt time.Time `json:"updated_at"`
}

type CustomerPayment struct {
	ID           uuid.UUID      `json:"id"`
	Status       string         `json:"status"`
	SuccessAt    sql.NullTime   `json:"success_at"`
	FailedReason sql.NullString `json:"failed_reason"`
	// When payment created
	CreatedAt time.Time `json:"created_at"`
	// When payment created
	UpdatedAt       time.Time `json:"updated_at"`
	CustomerOrderID uuid.UUID `json:"customer_order_id"`
	PaymentOptionID int32     `json:"payment_option_id"`
}

type Event struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	StartDate   sql.NullTime   `json:"start_date"`
	EndDate     sql.NullTime   `json:"end_date"`
	Prefix      string         `json:"prefix"`
	// When event created
	CreatedAt time.Time `json:"created_at"`
	// When event created
	UpdatedAt time.Time `json:"updated_at"`
}

type OrderTicket struct {
	Qty             sql.NullInt32 `json:"qty"`
	TicketID        uuid.UUID     `json:"ticket_id"`
	CustomerOrderID uuid.UUID     `json:"customer_order_id"`
}

type PaymentOption struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Ticket struct {
	ID           uuid.UUID    `json:"id"`
	SerialNumber string       `json:"serial_number"`
	PurchaseDate sql.NullTime `json:"purchase_date"`
	// When ticket created
	CreatedAt time.Time `json:"created_at"`
	// When ticket created
	UpdatedAt        time.Time `json:"updated_at"`
	TicketCategoryID uuid.UUID `json:"ticket_category_id"`
}

type TicketCategory struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	Prefix    string       `json:"prefix"`
	Qty       int64        `json:"qty"`
	Price     int64        `json:"price"`
	StartDate sql.NullTime `json:"start_date"`
	EndDate   sql.NullTime `json:"end_date"`
	// When ticket category created
	CreatedAt time.Time `json:"created_at"`
	// When ticket category created
	UpdatedAt time.Time      `json:"updated_at"`
	Area      sql.NullString `json:"area"`
	EventID   uuid.UUID      `json:"event_id"`
}
