DROP TABLE IF EXISTS "public"."payment_option" CASCADE;
DROP TABLE IF EXISTS "customer_payment" CASCADE;
DROP TABLE IF EXISTS "order_ticket" CASCADE;
DROP TABLE IF EXISTS "customer_order" CASCADE;
DROP TABLE IF EXISTS "customer" CASCADE;
DROP TABLE IF EXISTS "ticket" CASCADE;
DROP TABLE IF EXISTS "ticket_category" CASCADE;
DROP TABLE IF EXISTS "event" CASCADE;
